// <auto-generated />
using Chat.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chat.Migrations
{
    [DbContext(typeof(MysqlDB))]
    [Migration("20230502094253_UserAcceptsInvites")]
    partial class UserAcceptsInvites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Chat.Models.Invite", b =>
                {
                    b.Property<string>("uuid")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("accessKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<string>("useruuid")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("uuid");

                    b.HasIndex("useruuid");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("Chat.Models.User", b =>
                {
                    b.Property<string>("uuid")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("acceptsInvites")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("encryptedUserData")
                        .HasMaxLength(131072)
                        .HasColumnType("longtext");

                    b.Property<string>("publicKey")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("uuid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Chat.Models.Invite", b =>
                {
                    b.HasOne("Chat.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("useruuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
